name: ci-backend

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
  NIJIVOICE_API_KEY: ${{ secrets.NIJIVOICE_API_KEY }}
  R2_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT_URL }}
  R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
  R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
  R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}

jobs:
  ci:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker set up
        run: |
          docker compose up --build -d
      - name: run CI
        run: |
          make ci
